# Site settings
title: Professional portfolio
description: Webpage that showcase my professional experience technologies and career path.
baseurl:  # the subpath of your site, e.g. /blog
url:    # the base hostname & protocol for your site e.g. http://alfredamboka.online

# User settings
username: Alfred Amboka
user_description: I am a passionate Geomatic engineer and GIS specialist. 
Currently a student at JKUAT undertaking Bsc. Geomatic Engineering and Geospatial Information Systems. 
I have two years experience in GIS and spatial analysis, Remote sensing, Photogrammetry,Basic web development, 
database management seeking to create an impact using this skills. The future is key and therefore, I  have interest in Location Intelligence and Artificial 
Intelligence in general. I support team work and collaborations thus am a leader.

user_title: Geospatial Engineer and GIS Specialist | Web Developer 
email: alfredamboxan.wegner@gmail.com
twitter_username: amboka_w
github_username:  alfredamboka
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
